Makefile: ignore "set but unused variable" warnings too
After the following diff

	--- a/out/test-step_by/step_by.c
	+++ b/out/test-step_by/step_by.c
	@@ -17,10 +17,10 @@ const_int32_t__x2;
	 void step_by_bar(void)
	 {
	   int32_t i0 = 0;
	-  for (int32_t i = 0; i < 24; i = i + (int32_t)(size_t)6U)
	+  for (int32_t i = 0; i < 24; i += (int32_t)(size_t)6U)
	   {
	     int32_t j = i;
	-    i0 = i0 + j;
	+    i0 += j;
	   }
	   /* original Rust expression is not an lvalue in C */
	   int32_t lvalue = 36;

Clang changes its warning to say "

	step_by.c:34:11: error: variable 'i0' set but not used [-Werror,-Wunused-but-set-variable]
	   34 |   int32_t i0 = 0;
	      |           ^

So add that to the ignore list, which I believe is this intention.